/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CCourseManage;
import Controller.CNewStudentRegister;
import Controller.Cstudentmanage;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niman
 */
public class ManageCourse extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourse
     */
    public ManageCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_deletecourse = new javax.swing.JButton();
        btn_updatecourse = new javax.swing.JButton();
        btn_addcourse2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txt_cfee = new javax.swing.JTextField();
        jLabel_coursename = new javax.swing.JLabel();
        jLabel_courseperiod = new javax.swing.JLabel();
        jLabel_courseperiod1 = new javax.swing.JLabel();
        txt_cname = new javax.swing.JTextField();
        txt_cduration = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Course = new javax.swing.JTable();
        btn_coursesave = new javax.swing.JButton();
        btn_view1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel_ = new javax.swing.JLabel();
        jLabel_courseperiod2 = new javax.swing.JLabel();
        txt_ucname = new javax.swing.JTextField();
        jLabel_courseperiod3 = new javax.swing.JLabel();
        txt_ucfee = new javax.swing.JTextField();
        txt_ucduration = new javax.swing.JTextField();
        btn_cupdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_Courseupdate = new javax.swing.JTable();
        btn_cview2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_coursename1 = new javax.swing.JLabel();
        txt_dcname = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabel_dtable = new javax.swing.JTable();
        btn_cview3 = new javax.swing.JButton();
        btn_coursedelete1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1337, 871));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(314, 771));

        btn_deletecourse.setBackground(new java.awt.Color(102, 102, 255));
        btn_deletecourse.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_deletecourse.setForeground(new java.awt.Color(0, 0, 0));
        btn_deletecourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btn_deletecourse.setText("Delete Course");
        btn_deletecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecourseActionPerformed(evt);
            }
        });

        btn_updatecourse.setBackground(new java.awt.Color(102, 102, 255));
        btn_updatecourse.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_updatecourse.setForeground(new java.awt.Color(0, 0, 0));
        btn_updatecourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-icon.png"))); // NOI18N
        btn_updatecourse.setText("Update Course");
        btn_updatecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatecourseActionPerformed(evt);
            }
        });

        btn_addcourse2.setBackground(new java.awt.Color(102, 102, 255));
        btn_addcourse2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_addcourse2.setForeground(new java.awt.Color(0, 0, 0));
        btn_addcourse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-icon.png"))); // NOI18N
        btn_addcourse2.setText("Add Course");
        btn_addcourse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcourse2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));

        btn_Back.setBackground(new java.awt.Color(102, 102, 255));
        btn_Back.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(0, 0, 0));
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Back");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_updatecourse, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(btn_deletecourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addcourse2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btn_addcourse2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(btn_updatecourse)
                .addGap(61, 61, 61)
                .addComponent(btn_deletecourse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jPanel2.setBackground(new java.awt.Color(43, 39, 228));
        jPanel2.setPreferredSize(new java.awt.Dimension(653, 135));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Mangement System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        txt_cfee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_coursename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_coursename.setText("Course Name");

        jLabel_courseperiod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_courseperiod.setText("Course Fees");

        jLabel_courseperiod1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_courseperiod1.setText("Course Duration");

        txt_cname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_cduration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Tabel_Course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_name", "Course_Duration", "Course_Fees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel_Course);

        btn_coursesave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_coursesave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save-icon.png"))); // NOI18N
        btn_coursesave.setText("Save");
        btn_coursesave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coursesaveActionPerformed(evt);
            }
        });

        btn_view1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_view1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-icon.png"))); // NOI18N
        btn_view1.setText("View");
        btn_view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_courseperiod1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jLabel_coursename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_courseperiod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_cname, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addComponent(txt_cduration, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_view1)
                                .addComponent(txt_cfee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_coursesave, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1471, 1471, 1471))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_coursename, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_courseperiod1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cduration, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_courseperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cfee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_coursesave)
                            .addComponent(btn_view1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jLabel_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_.setText("Course Name");

        jLabel_courseperiod2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_courseperiod2.setText("Course Duration");

        txt_ucname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel_courseperiod3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_courseperiod3.setText("Course Fees");

        txt_ucfee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_ucduration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_cupdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-update-48.png"))); // NOI18N
        btn_cupdate.setText("Update");
        btn_cupdate.setPreferredSize(new java.awt.Dimension(139, 75));
        btn_cupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cupdateActionPerformed(evt);
            }
        });

        Tabel_Courseupdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_name", "Course_Duration", "Course_Fees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabel_Courseupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_CourseupdateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabel_Courseupdate);

        btn_cview2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cview2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-icon.png"))); // NOI18N
        btn_cview2.setText("View");
        btn_cview2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cview2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(298, 298, 298))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_cview2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_courseperiod2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_courseperiod3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ucduration, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ucfee, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ucname, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1522, 1522, 1522))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ucname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_courseperiod2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ucduration, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_courseperiod3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ucfee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_cview2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jLabel_coursename1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_coursename1.setText("Course Name");

        txt_dcname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Tabel_dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_name", "Course_Duration", "Course_Fees"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabel_dtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_dtableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabel_dtable);

        btn_cview3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cview3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-icon.png"))); // NOI18N
        btn_cview3.setText("View");
        btn_cview3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cview3ActionPerformed(evt);
            }
        });

        btn_coursedelete1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_coursedelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btn_coursedelete1.setText("Delete");
        btn_coursedelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coursedelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel_coursename1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dcname, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_coursedelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cview3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1511, 1511, 1511))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_coursename1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dcname, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_coursedelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cview3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 2441, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deletecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletecourseActionPerformed
       jTabbedPane1.setSelectedIndex(2);
       
        

    }//GEN-LAST:event_btn_deletecourseActionPerformed

    private void btn_updatecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatecourseActionPerformed
         jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_updatecourseActionPerformed

    private void btn_addcourse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcourse2ActionPerformed
         jTabbedPane1.setSelectedIndex(0);
                  
                 
                 
    }//GEN-LAST:event_btn_addcourse2ActionPerformed

    private void btn_coursesaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coursesaveActionPerformed
       String Cname;
       int Cfee,Cduration;
       
       
       
       try{
           Cname=txt_cname.getText();
           Cduration=Integer.parseInt(txt_cduration.getText());
           Cfee=Integer.parseInt(txt_cfee.getText());
           
           CCourseManage course=new CCourseManage();
           course.addCourse(Cname,Cfee,Cduration);
           
            //calling viewstudentData Method
            CCourseManage st1=new CCourseManage();
            ResultSet rs=st1.viewCourse();
            DefaultTableModel model = (DefaultTableModel)Tabel_Course.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
            
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
           
           
       }
       catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null,"Wrong type conversion");
           
       }
       catch(SQLException e)
       {
           
           JOptionPane.showMessageDialog(rootPane,"Course name already exist");
           
       }
    }//GEN-LAST:event_btn_coursesaveActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        Dashboard st1=new Dashboard();
        this.hide();
        st1.setVisible(true);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_cupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cupdateActionPerformed
        try{
           String Cname=txt_ucname.getText();
           int Cduration=Integer.parseInt(txt_ucduration.getText());
           int Cfee=Integer.parseInt(txt_ucfee.getText());
           
           CCourseManage course=new CCourseManage();
           course.updateCourse(Cname, Cfee, Cduration);
           
           //view updateed table
            ResultSet rs=course.viewCourse();
            DefaultTableModel model = (DefaultTableModel)Tabel_Courseupdate .getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
            
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
           
        }
        catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null,"Wrong type conversion");
           
       }
       catch(Exception e)
       {
           
           JOptionPane.showMessageDialog(null,e.getMessage());
           
       }
        
    }//GEN-LAST:event_btn_cupdateActionPerformed

    private void btn_cview3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cview3ActionPerformed
          try{
            CCourseManage view=new CCourseManage();
            ResultSet rs=view.viewCourse();
            DefaultTableModel model = (DefaultTableModel)Tabel_dtable.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,"Sql query error","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_cview3ActionPerformed

    private void btn_coursedelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coursedelete1ActionPerformed
        String Sname;
        try{
            Sname=txt_dcname.getText();
            CCourseManage c1=new CCourseManage();
            c1.deleteCource(Sname);
            //deleted table
             CCourseManage view=new CCourseManage();
            ResultSet rs=view.viewCourse();
            DefaultTableModel model = (DefaultTableModel)Tabel_dtable.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,"Sql query error","Error",JOptionPane.ERROR_MESSAGE);
        
        }
        
    }//GEN-LAST:event_btn_coursedelete1ActionPerformed

    private void btn_cview2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cview2ActionPerformed
         try{
            CCourseManage view=new CCourseManage();
            ResultSet rs=view.viewCourse();
            DefaultTableModel model = (DefaultTableModel)Tabel_Courseupdate.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,"Sql query error","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_cview2ActionPerformed

    private void btn_view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view1ActionPerformed
        
        //calling viewstudentData Method
        try{
            CCourseManage view=new CCourseManage();
            ResultSet rs=view.viewCourse();
            DefaultTableModel model = (DefaultTableModel)Tabel_Course.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
                model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3)});
            }
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,"Sql query error","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_view1ActionPerformed

    private void Tabel_CourseupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_CourseupdateMouseClicked
        DefaultTableModel model = (DefaultTableModel)Tabel_Courseupdate.getModel();
         int selectindex=Tabel_Courseupdate.getSelectedRow();
         
         txt_ucname.setText(model.getValueAt(selectindex, 0).toString());
          txt_ucduration.setText(model.getValueAt(selectindex, 1).toString());
           txt_ucfee.setText(model.getValueAt(selectindex, 2).toString());
            
               
                                                
    }//GEN-LAST:event_Tabel_CourseupdateMouseClicked

    private void Tabel_dtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_dtableMouseClicked
       DefaultTableModel model = (DefaultTableModel)Tabel_dtable.getModel();
         int selectindex=Tabel_dtable.getSelectedRow();
         
         txt_dcname.setText(model.getValueAt(selectindex, 0).toString());
    }//GEN-LAST:event_Tabel_dtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_Course;
    private javax.swing.JTable Tabel_Courseupdate;
    private javax.swing.JTable Tabel_dtable;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_addcourse2;
    private javax.swing.JButton btn_coursedelete1;
    private javax.swing.JButton btn_coursesave;
    private javax.swing.JButton btn_cupdate;
    private javax.swing.JButton btn_cview2;
    private javax.swing.JButton btn_cview3;
    private javax.swing.JButton btn_deletecourse;
    private javax.swing.JButton btn_updatecourse;
    private javax.swing.JButton btn_view1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_;
    private javax.swing.JLabel jLabel_coursename;
    private javax.swing.JLabel jLabel_coursename1;
    private javax.swing.JLabel jLabel_courseperiod;
    private javax.swing.JLabel jLabel_courseperiod1;
    private javax.swing.JLabel jLabel_courseperiod2;
    private javax.swing.JLabel jLabel_courseperiod3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_cduration;
    private javax.swing.JTextField txt_cfee;
    private javax.swing.JTextField txt_cname;
    private javax.swing.JTextField txt_dcname;
    private javax.swing.JTextField txt_ucduration;
    private javax.swing.JTextField txt_ucfee;
    private javax.swing.JTextField txt_ucname;
    // End of variables declaration//GEN-END:variables
}
