/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Cstudentmanage;
import com.mysql.cj.jdbc.result.ResultSetFactory;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.InputMismatchException;

/**
 *
 * @author niman
 */
public class ManageStudent extends javax.swing.JFrame {
    
    /**
     * Creates new form ManageStudent
     */
    public ManageStudent() {
        initComponents();
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Manage_student_Logo = new javax.swing.JLabel();
        btn_studentdelete = new javax.swing.JButton();
        btn_studentupdate = new javax.swing.JButton();
        btn_studentview = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Tab_Delete = new javax.swing.JPanel();
        btn_sdelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_studentdata2 = new javax.swing.JTable();
        btn_sview = new javax.swing.JButton();
        txt_Dsid = new javax.swing.JTextField();
        Tab_view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_studentdata = new javax.swing.JTable();
        label_Mname = new javax.swing.JLabel();
        txt_Msid = new javax.swing.JTextField();
        label_Msid1 = new javax.swing.JLabel();
        label_Memail = new javax.swing.JLabel();
        label_Maddress = new javax.swing.JLabel();
        label_Mdob = new javax.swing.JLabel();
        label_MTel = new javax.swing.JLabel();
        label_Mcourse = new javax.swing.JLabel();
        txt_Mname = new javax.swing.JTextField();
        txt_Memail = new javax.swing.JTextField();
        txt_Maddress = new javax.swing.JTextField();
        txt_Mtel = new javax.swing.JTextField();
        jDateChooser_Mdob = new com.toedter.calendar.JDateChooser();
        btn_SDupdate = new javax.swing.JButton();
        txt_Mcourse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(314, 771));

        Manage_student_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/managementhom-icon.png"))); // NOI18N

        btn_studentdelete.setBackground(new java.awt.Color(102, 102, 255));
        btn_studentdelete.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_studentdelete.setForeground(new java.awt.Color(0, 0, 0));
        btn_studentdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\niman\\OneDrive\\Desktop\\EAD CourseWork\\icons8-delete-48.png")); // NOI18N
        btn_studentdelete.setText("Delete");
        btn_studentdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentdeleteActionPerformed(evt);
            }
        });

        btn_studentupdate.setBackground(new java.awt.Color(102, 102, 255));
        btn_studentupdate.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_studentupdate.setForeground(new java.awt.Color(0, 0, 0));
        btn_studentupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-icon.png"))); // NOI18N
        btn_studentupdate.setText("Update");
        btn_studentupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentupdateActionPerformed(evt);
            }
        });

        btn_studentview.setBackground(new java.awt.Color(102, 102, 255));
        btn_studentview.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btn_studentview.setForeground(new java.awt.Color(0, 0, 0));
        btn_studentview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-icon.png"))); // NOI18N
        btn_studentview.setText("View");
        btn_studentview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentviewActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(144, 59));

        btn_Back.setBackground(new java.awt.Color(102, 102, 255));
        btn_Back.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(0, 0, 0));
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Back");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Manage_student_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_studentdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_studentview, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_studentupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Manage_student_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btn_studentview)
                .addGap(70, 70, 70)
                .addComponent(btn_studentupdate)
                .addGap(61, 61, 61)
                .addComponent(btn_studentdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(43, 39, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(653, 135));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Tab_Delete.setBackground(new java.awt.Color(255, 255, 204));
        Tab_Delete.setForeground(new java.awt.Color(255, 255, 204));

        btn_sdelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sdelete.setForeground(new java.awt.Color(0, 0, 0));
        btn_sdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-delete-48.png"))); // NOI18N
        btn_sdelete.setText("Delete");
        btn_sdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sdeleteActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Student_Id");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));

        table_studentdata2.setBackground(new java.awt.Color(255, 255, 255));
        table_studentdata2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table_studentdata2.setForeground(new java.awt.Color(0, 0, 0));
        table_studentdata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sid", "Sname", "Email", "Address", "Course", "Telephone", "Dob"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_studentdata2.setPreferredSize(new java.awt.Dimension(836, 506));
        table_studentdata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_studentdata2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_studentdata2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_sview.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sview.setForeground(new java.awt.Color(0, 0, 0));
        btn_sview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-icon.png"))); // NOI18N
        btn_sview.setText("View");
        btn_sview.setPreferredSize(new java.awt.Dimension(125, 59));
        btn_sview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tab_DeleteLayout = new javax.swing.GroupLayout(Tab_Delete);
        Tab_Delete.setLayout(Tab_DeleteLayout);
        Tab_DeleteLayout.setHorizontalGroup(
            Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_DeleteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sdelete, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGroup(Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_DeleteLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(txt_Dsid, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab_DeleteLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btn_sview, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        Tab_DeleteLayout.setVerticalGroup(
            Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_DeleteLayout.createSequentialGroup()
                .addGroup(Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_DeleteLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Dsid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(Tab_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sview, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Tab_DeleteLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", Tab_Delete);

        Tab_view.setBackground(new java.awt.Color(255, 255, 204));

        table_studentdata.setBackground(new java.awt.Color(255, 255, 255));
        table_studentdata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table_studentdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sid", "Sname", "Email", "Address", "Course", "Telephone", "Dob"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_studentdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_studentdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_studentdata);

        label_Mname.setBackground(new java.awt.Color(204, 255, 204));
        label_Mname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Mname.setForeground(new java.awt.Color(0, 0, 0));
        label_Mname.setText("Student_Name");

        txt_Msid.setBackground(new java.awt.Color(255, 255, 255));
        txt_Msid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Msid.setForeground(new java.awt.Color(0, 0, 0));

        label_Msid1.setBackground(new java.awt.Color(204, 255, 204));
        label_Msid1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Msid1.setForeground(new java.awt.Color(0, 0, 0));
        label_Msid1.setText("Student_id");

        label_Memail.setBackground(new java.awt.Color(204, 255, 204));
        label_Memail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Memail.setForeground(new java.awt.Color(0, 0, 0));
        label_Memail.setText("Email");

        label_Maddress.setBackground(new java.awt.Color(204, 255, 204));
        label_Maddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Maddress.setForeground(new java.awt.Color(0, 0, 0));
        label_Maddress.setText("Address");

        label_Mdob.setBackground(new java.awt.Color(204, 255, 204));
        label_Mdob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Mdob.setForeground(new java.awt.Color(0, 0, 0));
        label_Mdob.setText("Dob");

        label_MTel.setBackground(new java.awt.Color(204, 255, 204));
        label_MTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_MTel.setForeground(new java.awt.Color(0, 0, 0));
        label_MTel.setText("Telephone");

        label_Mcourse.setBackground(new java.awt.Color(204, 255, 204));
        label_Mcourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_Mcourse.setForeground(new java.awt.Color(0, 0, 0));
        label_Mcourse.setText("Course");

        txt_Mname.setBackground(new java.awt.Color(255, 255, 255));
        txt_Mname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Mname.setForeground(new java.awt.Color(0, 0, 0));

        txt_Memail.setBackground(new java.awt.Color(255, 255, 255));
        txt_Memail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Memail.setForeground(new java.awt.Color(0, 0, 0));

        txt_Maddress.setBackground(new java.awt.Color(255, 255, 255));
        txt_Maddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Maddress.setForeground(new java.awt.Color(0, 0, 0));

        txt_Mtel.setBackground(new java.awt.Color(255, 255, 255));
        txt_Mtel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Mtel.setForeground(new java.awt.Color(0, 0, 0));

        btn_SDupdate.setBackground(new java.awt.Color(255, 255, 255));
        btn_SDupdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_SDupdate.setForeground(new java.awt.Color(0, 0, 0));
        btn_SDupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save-icon.png"))); // NOI18N
        btn_SDupdate.setText("Update");
        btn_SDupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SDupdateActionPerformed(evt);
            }
        });

        txt_Mcourse.setBackground(new java.awt.Color(255, 255, 255));
        txt_Mcourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Mcourse.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Tab_viewLayout = new javax.swing.GroupLayout(Tab_view);
        Tab_view.setLayout(Tab_viewLayout);
        Tab_viewLayout.setHorizontalGroup(
            Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_viewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Msid1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Memail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Maddress, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_MTel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Mcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Mdob, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Msid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_Mdob, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Tab_viewLayout.createSequentialGroup()
                        .addComponent(txt_Memail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_SDupdate))
                    .addComponent(txt_Maddress, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Mcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Mtel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(903, Short.MAX_VALUE))
        );
        Tab_viewLayout.setVerticalGroup(
            Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_viewLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addGroup(Tab_viewLayout.createSequentialGroup()
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Msid1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Msid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Tab_viewLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txt_Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tab_viewLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Memail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Memail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Tab_viewLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btn_SDupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Maddress, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Maddress, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Mcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Mcourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_MTel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Mtel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Tab_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_Mdob, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_Mdob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", Tab_view);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2044, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studentviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentviewActionPerformed
         
        jTabbedPane1.setSelectedIndex(1);
        Cstudentmanage student=new Cstudentmanage();
        ResultSet rs=student.viewStudentData();
         
        
        
            
        try{
          
            
            DefaultTableModel model = (DefaultTableModel)table_studentdata.getModel();
           
            model.setRowCount(0);
            
            while(rs.next())
            {
              //ADD DATA TO TABLE
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }
            
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
            
        }
       
         
         
    }//GEN-LAST:event_btn_studentviewActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        Dashboard st1=new Dashboard();
        this.hide();
        st1.setVisible(true);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_SDupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SDupdateActionPerformed
        String Name,Email,Address,Course,R_Date;
        int Tel,Sid;
        
        try{
            Sid=Integer.parseInt(txt_Msid.getText());
            Name=txt_Mname.getText();
            Email=txt_Memail.getText();
            Address=txt_Maddress.getText();
            Course=txt_Mcourse.getText();
            Tel=Integer.parseInt(txt_Mtel.getText());

            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            R_Date=sdf.format(jDateChooser_Mdob.getDate());

            Cstudentmanage st1=new Cstudentmanage();
            st1.updateStudentData(Sid,Name,Email,Address,Course,Tel,R_Date);
            
            //calling viewstudentData Method
            ResultSet rs=st1.viewStudentData();
            DefaultTableModel model = (DefaultTableModel)table_studentdata.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
            
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }

        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Enter valid data types");

        }
        catch(NullPointerException e2)
        {
            JOptionPane.showMessageDialog(null,"Check all fields");
            
        }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
            
        }
    }//GEN-LAST:event_btn_SDupdateActionPerformed

    private void table_studentdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_studentdataMouseClicked
        //table mouseclick
        DefaultTableModel model = (DefaultTableModel)table_studentdata.getModel();
         int selectindex=table_studentdata.getSelectedRow();
         
         txt_Msid.setText(model.getValueAt(selectindex, 0).toString());
          txt_Mname.setText(model.getValueAt(selectindex, 1).toString());
           txt_Memail.setText(model.getValueAt(selectindex, 2).toString());
            txt_Maddress.setText(model.getValueAt(selectindex, 3).toString());
             txt_Mcourse.setText(model.getValueAt(selectindex, 4).toString());
              txt_Mtel.setText(model.getValueAt(selectindex, 5).toString());
               
               jDateChooser_Mdob.setDateFormatString(model.getValueAt(selectindex , 6).toString());
    }//GEN-LAST:event_table_studentdataMouseClicked

    private void btn_sdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sdeleteActionPerformed
        int Sid;
        try{
            Sid=Integer.parseInt(txt_Dsid.getText());
             Cstudentmanage student=new Cstudentmanage();
             student.deleteStudent(Sid);
             
             //calling viewstudentData Method
            Cstudentmanage st1=new Cstudentmanage();
            ResultSet rs=st1.viewStudentData();
            DefaultTableModel model = (DefaultTableModel)table_studentdata2.getModel();
            model.setRowCount(0);
            
            while(rs.next())
            {
            
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }

        
        
        
        }
        catch(InputMismatchException e)
        {
            
            JOptionPane.showMessageDialog(null,"Wrong Type input Error","Error",JOptionPane.ERROR_MESSAGE);
            
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,"Sql query error","Error",JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException e)
        {
            
            JOptionPane.showMessageDialog(null,"Wrong type conversion","Error",JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btn_sdeleteActionPerformed

    private void btn_studentupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentupdateActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_studentupdateActionPerformed

    private void btn_studentdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentdeleteActionPerformed
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_studentdeleteActionPerformed

    private void table_studentdata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_studentdata2MouseClicked
        DefaultTableModel model = (DefaultTableModel)table_studentdata2.getModel();
         int selectindex=table_studentdata2.getSelectedRow();
         
         txt_Dsid.setText(model.getValueAt(selectindex, 0).toString());
    }//GEN-LAST:event_table_studentdata2MouseClicked

    private void btn_sviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sviewActionPerformed
         Cstudentmanage student=new Cstudentmanage();
        ResultSet rs=student.viewStudentData();
         
        
        
            
        try{
          
            
            DefaultTableModel model = (DefaultTableModel)table_studentdata2.getModel();
           
            model.setRowCount(0);
            
            while(rs.next())
            {
              //ADD DATA TO TABLE
               model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
            }
            
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
            
        }
       
    }//GEN-LAST:event_btn_sviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Manage_student_Logo;
    private javax.swing.JPanel Tab_Delete;
    private javax.swing.JPanel Tab_view;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_SDupdate;
    private javax.swing.JButton btn_sdelete;
    private javax.swing.JButton btn_studentdelete;
    private javax.swing.JButton btn_studentupdate;
    private javax.swing.JButton btn_studentview;
    private javax.swing.JButton btn_sview;
    private com.toedter.calendar.JDateChooser jDateChooser_Mdob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_MTel;
    private javax.swing.JLabel label_Maddress;
    private javax.swing.JLabel label_Mcourse;
    private javax.swing.JLabel label_Mdob;
    private javax.swing.JLabel label_Memail;
    private javax.swing.JLabel label_Mname;
    private javax.swing.JLabel label_Msid1;
    private javax.swing.JTable table_studentdata;
    private javax.swing.JTable table_studentdata2;
    private javax.swing.JTextField txt_Dsid;
    private javax.swing.JTextField txt_Maddress;
    private javax.swing.JTextField txt_Mcourse;
    private javax.swing.JTextField txt_Memail;
    private javax.swing.JTextField txt_Mname;
    private javax.swing.JTextField txt_Msid;
    private javax.swing.JTextField txt_Mtel;
    // End of variables declaration//GEN-END:variables
}
